### ISSUE TITLE
能不能分享一下用到的package或者data

### ISSUE THREAD

**Issue by willguxy** [bbfamily/abu#1]
感谢分享。ipython notebook里用到的一些package，我在网上没找到。有些是proprietary的，付费的API之类的吧？包括data也是，要是有直接可以下载的data，没有package也没关系，至少做的时候是apple vs apple的比较。有code但是不能重复以及在你的基础上继续挖掘，感觉很遗憾啊

**Comment by bbfamily** [comment]
https://github.com/bbfamily/abu/tree/master/src git上里面有的代码就是文章中主要涉及的全部代码

但是git上不是所有代码，没有交易系统等基础库，工具库等，由于我现在在写一本关于股票量化方面的书，会涉及到文章里的一些内容，出版社方面不希望我现在开源代码，但是一定会开源，最晚等书出版发行以后，希望理解
