### ISSUE TITLE
无法安装abupy

### ISSUE THREAD

**Issue by yslhzj** [bbfamily/abu#13]
pip install abupy后出现如下提示
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    building 'statsmodels.tsa.kalmanf.kalman_loglike' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

安装Microsoft Visual C++ 14.0后,依然安装不成功,求助!

**Comment by bbfamily** [comment]
请按照教程http://www.abuquant.com/lecture/lecture_0.html中使用conda的python开发环境
