### ISSUE TITLE
有真实交易的接口吗？

### ISSUE THREAD

**Issue by joyruby** [bbfamily/abu#14]
可以使用这套框架 写购买策略吗

**Comment by bbfamily** [comment]
abupy本质上不提供及维护数据源，内置的数据源为爬取百度，腾讯，新浪，网易，火币等第三方，只做教程示例使用，并不能保证一直的连通性，建议外接自己的数据源，具体请阅读教程第19节 http://www.abuquant.com/lecture/lecture_19.html
