### ISSUE TITLE
看您的代码的疑问

### ISSUE THREAD

**Issue by starfire-lzd** [bbfamily/abu#16]
阿布老师，您好：
       我看了您的代码，找到的都是关于回测模块的内容，请问您的这个框架中有实盘交易的模块么，如果有，应该怎么使用，我看到在您的量化课堂中的第一节有提到实盘模块的。

**Comment by bbfamily** [comment]
您好，您说的量化课堂中的第一节有提到实盘模块是在针对量化交易系统的一般性结构介绍，并不是说我会开源实盘系统，希望理解，本来一开始只是写书时想开源一部分，后来觉着既然开源了，会用得写个教程，但是现在感觉占用我时间太多，最初只是因为和我家孩子一起玩的最好的一个孩子父母都是大学老师，一起玩的时候聊天发现我们父母都都是无业游民，当时正好有个出版社找我写书，我想以后孩子上学什么的能写个爸爸干点啥，不至于太拖累为难孩子，量化最终要做出还得要靠自己独立思考，独立交易，祝好！
