### ISSUE TITLE
更新A 股本地数据，截止时间反而缩短

### ISSUE THREAD

**Issue by huerbt** [bbfamily/abu#17]
运行环境：Mac High Sierra 10.13.3

现象：3月9日更新了本地数据（2017-03-09 到2018-03-09），并检查kl_pd确实有9号的数据。3月12日更新数据（2017-03-12 到2018-03-12）时发现kl_pd只有截止到8号的数据了。查看data/csv目录下的文件，文件名显示是到20180312。分别试了百度，腾讯的数据源都是这个问题，后来只有把csv下的文件都删除，再更新就没事了。

更新代码如下：
todayStr = '2018-03-12'
stratDateStr = '2017-03-12'
#更新数据
 abupy.env.g_market_source = EMarketSourceType.E_MARKET_SOURCE_bd
abupy.env.g_data_cache_type = EDataCacheType.E_DATA_CACHE_CSV
abu.run_kl_update(start=stratDateStr,end=todayStr,market=EMarketTargetType.E_MARKET_TARGET_CN, n_jobs=16)

**Comment by bbfamily** [comment]
普通更新模式下会根据最后更新日期决定是否反复请求网络，所以切换数据源也不会更新，env中设置E_DATA_FETCH_FORCE_NET可强制使用网络进行更新，另外abupy里内置里百度，腾讯，网易，火币等数据源，只为做教程示例，不做接口维护，不能保证网络更新成功，建议教程中的示例需要全市场的直接下载教程中的那个已经拼装好的csv压缩包，实际做时建议按照教程第19节接上自己稳定的数据源
