### ISSUE TITLE
TypeError: '>=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by evyn120** [bbfamily/abu#18]
![image](https://user-images.githubusercontent.com/24862888/38098895-bd805cb0-33ab-11e8-92b0-9168cedb9894.png)

**Comment by bbfamily** [comment]
感谢，您sklearn的版本应该使用的是beta或者其它非纯数字版本，由于fixes的代码本来就是尝试接近版本兼容问题，所以github上的代码已经修改为如果遇到这种情况不去检测版本兼容，但依然建议使用教程0：http://www.abuquant.com/lecture/lecture_0.html中的conda4.4统一运行环境

**Comment by evyn120** [comment]
用惯pycharm了，那是要换个其他什么时刻、learn版本么？纯数字的？

**Comment by bbfamily** [comment]
pycharm也是支持conda的，现在github上的代码已经把fixes做了保护，不会遇到第三方的beta版本出错，可以尝试更新代码

**Comment by evyn120** [comment]
好的 ，已解决，谢谢
