### ISSUE TITLE
用ABuSymbolPd.make_kl_df()方法获取期货数据时，date、date_week字段数据类型有些问题..

### ISSUE THREAD

**Issue by ronlym** [bbfamily/abu#20]
在学abupy_lecture/19-数据源(ABU量化使用文档).ipynb时，发现配好数据源并用make_kl_df()方法获取期货数据时，日期字段会奇怪的变为“乱码”
![2018-05-09 7 23 25](https://user-images.githubusercontent.com/25770147/39812360-ecdded32-53be-11e8-8bc6-d8f859dfae2e.png)
随着源码查看了格式化日期的步骤，没有发现异常，前后日志输出都是正常的从string转到int，但不懂为什么最后将dataframe绘制出来时会变成这个样子。
同样的获取股票数据没有类似问题，只有期货会这样，还有date_week字段，本应为int，但期货数据中最后变为float（或str），没找到原因。求解答。
教程中例子也会有同样问题

**Comment by bbfamily** [comment]
不是乱码，是科学计数法显示，不影响正常使用，可以使用iloc拿出一行后使用date查看，这个数据只是因为是float，因为数据源返回的是float，如在意显示可使用astype(int)转换int后

**Comment by ronlym** [comment]
已经用astype转换过int了大佬。。而且是你源码里已经写好的，跟股票用的是同一种方法，只有期货才有这种情况。觉得还是有些其他原因。

**Comment by ronlym** [comment]
而且日期肯定都是处理过的，ABuDateUtil.date_str_to_int，返回回来又astype了一遍。但始终有这种情况。算了，确实不影响使用。
