### ISSUE TITLE
关于画动态图（interative）的问题，目前matplotlib生成的静态图不可交互。

### ISSUE THREAD

**Issue by githubcyc** [bbfamily/abu#21]
如[文章](https://www.abuquant.com/lecture/lecture_13.htmll) 的图片是静态的， 光标放上去没有数据显示，所以想画成有数据交互的html。

可行方案：
* [Dash](https://github.com/plotly/dash)
* [pyecharts](http://pyecharts.org/#/zh-cn/charts?id=line%EF%BC%88%E6%8A%98%E7%BA%BF%E9%9D%A2%E7%A7%AF%E5%9B%BE%EF%BC%89)
Thanks for ur attention.
想寻求一下见解。

**Comment by bbfamily** [comment]
根据视觉需求，功能需求，时间成本综合考虑吧
