### ISSUE TITLE
回测成功后, 如何将模型用于实际交易?

### ISSUE THREAD

**Issue by hongbin0908** [bbfamily/abu#23]
例子全是讲回测模块的, 没有讲实时模块的.

**Comment by bbfamily** [comment]
是的，没开源实盘，没有动力，我不接受私募的钱也不接受投资，更没想挣你们的钱，只拿自己的钱给自己做，本来一开始只是写书时想开源一部分，后来觉着既然开源了，会用得写个教程，但是现在感觉占用我时间太多，我是靠自己的交易时间挣钱，最初只是因为和我家孩子一起玩的最好的一个孩子父母都是大学老师，一起玩的时候聊天发现我们父母都都是无业游民，当时正好有个出版社找我写书，我想以后孩子上学什么的能写个爸爸干点啥，不至于太拖累为难孩子，说的比较直接，见谅，祝好！

**Comment by MaxieLj** [comment]
然而和你家孩子玩孩子并不知道你很有钱，哈哈。

**Comment by xiyanxiyan10** [comment]
作者很不错，弥补了使用ai进行量化的资料空白，我也买了你的书。

**Comment by XiaoYanWork** [comment]
你就说我是上市公司股东，或者说是软件公司CEO.
