### ISSUE TITLE
执行AbuMetricsBase.show_general() ，CPU跑到100%，然后就死机了！

### ISSUE THREAD

**Issue by liulion** [bbfamily/abu#25]
请教：
在测试 “20-A股全市场回测(ABU量化使用文档)”  章节中的第43步如下代码：
AbuMetricsBase.show_general(*abu_result_tuple_test, only_show_returns=True)

每次会把cpu 跑到100%，然后出现死机，我的机器是：8核 I7-4790K ，有什么办法降低CPU使用量，时间长点也没所谓。

**Comment by bbfamily** [comment]
应该是上一步run_loop_back可设置使用一个cpu，show_general只是显示，参数设置n_process_kl=1, n_process_pick=1, 具体请自行查阅见谅
