### ISSUE TITLE
请问安装问题

### ISSUE THREAD

**Issue by gaorufeng** [bbfamily/abu#3]
您好 我成功安装了 pip install abupy

我是否还需要 

git clone https://github.com/bbfamily/abu.git
C:\abu>c:\py36\python setup.py install

**Comment by bbfamily** [comment]
您好，目前最好是在github上clone项目，因为暂时功能还有很多未提交完全，比如ui界面可视化操作等等，而且github上有很多可直接运行的notebook示例
