### ISSUE TITLE
火币的数据源是不能用了吗？

### ISSUE THREAD

**Issue by calmzealA** [bbfamily/abu#31]
https://www.huobi.com/qt/staticmarket/btc_kline_100_json.js?length=504

现在并不返回json数据

**Comment by bbfamily** [comment]
对，没时间维护数据源，先有的源都是为了教程做参考，未来一定不能确保连通，需要接入自己的数据源，参考教程第19，祝好！

**Comment by houchenglong** [comment]
请问现在用什么数据源比较好@calmzeal
