### ISSUE TITLE
使用pip install abupy，matplotlib使用最新版本后报错问题

### ISSUE THREAD

**Issue by xhlgogo** [bbfamily/abu#33]
前辈你好，我是github新手，在绘制K线图时，使用了ABuMarketDrawing.py：
line 256，“import matplotlib.mpl_finance as mpf”报错，

将其改为
“import mpl_finance as mpf
 import matplotlib.dates as mpd”，
并将“mpf.date2num(d)”改为"mpd.date2num(d)"后可使用。

我可以将这个修改更新到github上吗？

**Comment by bbfamily** [comment]
您好，项目性质非商用，教程第0节中环境已建议使用conda4.4环境统一第三方版本问题，如需使用高版本可fork项目后自行维护，祝好！
