### ISSUE TITLE
关于abu选股的一点问题，请教下

### ISSUE THREAD

**Issue by sanitpeng** [bbfamily/abu#36]
你好， abu,
  在第八章， C8.py中，sample_821_1(),当使用真实数据，发现，选股器使用的kl_pd 总是2016年的数据。
  后来，发现是在ABuKLManager.py中，end 使用的是benchmark的第一个日期，并且您专门添加了注释说明取第一个日期（self.benchmark.kl_pd.index[0]），
这个地方不太明白，不是应该取当前的时间（self.benchmark.kl_pd.index[-1]）么？
谢谢！
代码：

    def _fetch_pick_stock_kl_pd(self, xd, target_symbol):

        # 从设置的择时benchmark中取第一个日期即为选股时段最后一个日期
        end = ABuDateUtil.timestamp_to_str(self.benchmark.kl_pd.index[0])

**Comment by bbfamily** [comment]
选股和择时是不同的时间序列, 否则就是使用了未来数据, 具体的您自己看吧, 具体代码其实我也忘了, 开源的这部分只是为了写书时需要, 没时间, 见谅, 祝好!

**Comment by sanitpeng** [comment]
多谢，我仔细看看，多谢你开源的代码，做了一个不错的开头。
