### ISSUE TITLE
pandas新版兼容问题

### ISSUE THREAD

**Issue by comeUpWithItLater** [bbfamily/abu#38]
`from abupy import GridSearch`
`GridSearch.fit( *** ` 运行的时候候出现大量warming:

/opt/conda/lib/python3.6/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

然后浏览器就崩溃了。

**Comment by bbfamily** [comment]
您好，感谢, 由于abupy只是写书时需要开源一部分代码, 并没时间和动机更新维护，且很难统一第三方库的接口，所以在教程0里建议使用conda4.4环境, 见谅, 祝好!
