### ISSUE TITLE
请教下基本面数据怎么接入？

### ISSUE THREAD

**Issue by suuuch** [bbfamily/abu#4]
买了作者的书，看的时候发现似乎没有基本面相关的数据？
能否告知想接入自定义数据怎么做比较好呢？

**Comment by bbfamily** [comment]
您好，感谢支持，有基本面相关的数据，在MarketBu/ABuSymbolStock/query_stock_info接口
也可以接入自己的数据，关于接入自己的数据请阅读教程下的‘第19节 数据源’ 相关内容。

另外关于基本面相关的后续也会有UI界面直接查询的功能，如下图：
<img width="180" alt="tes" src="https://user-images.githubusercontent.com/6149331/30783850-6b91b794-a17c-11e7-84ad-6a5d232d45d1.png">

**Comment by suuuch** [comment]
非常感谢。找到了。

**Comment by bbfamily** [comment]
别客气，感谢支持

**Comment by XiaoYanWork** [comment]
向神敬礼

**Comment by XiaoYanWork** [comment]
向大神敬礼
