### ISSUE TITLE
历史交易数据获取

### ISSUE THREAD

**Issue by G-F-CH** [bbfamily/abu#5]
买了书前天刚收到了，还没有细读，快速翻了一下。
想问一下书中回测用到的A股、美股数据去哪获取呢？比如我想回测比特币，从那里可以获取到历史数据呢。
另一个问题，如果要打造一个真正能实战的量化交易系统，是不是还得能获取实时交易数据啊？

**Comment by bbfamily** [comment]
关于数据请阅读教程第19节相关内容
