### ISSUE TITLE
获取数据源错误：day is out of range for month

### ISSUE THREAD

**Issue by leegive** [bbfamily/abu#7]
这个应该是个小BUG吧

**Comment by bbfamily** [comment]
您好，abupy里面的数据源只是为了教程的使用进行示例，因为都是爬取的百度，腾讯，网易，火币等的数据，数据连通性，性能等无法确定，不做接口维护，建议阅读教程只使用已经组装好的网盘那个csv数据，另外自己做的时候也明确说明了需要接入自己的数据源，相关教程在第19节 数据源 部分，祝好！
