### ISSUE TITLE
c10中sample_1052中cannot import name 'UmpMulFiter'问题

### ISSUE THREAD

**Issue by ZJianjin** [bbfamily/abu#8]
`C:\Python36\python.exe E:/abu-master/python/c10.py
enable example env will only read RomDataBu/df_kl.h5
disable example env
please wait! load_pickle....: C:\Users\PINC\abu\data\cache\n5_train_us_capital
please wait! load_pickle....: C:\Users\PINC\abu\data\cache\n5_train_us_benchmark
please wait! load_pickle....: C:\Users\PINC\abu\data\cache\n5_test_us_capital
please wait! load_pickle....: C:\Users\PINC\abu\data\cache\n5_test_us_benchmark
Traceback (most recent call last):
  File "E:/abu-master/python/c10.py", line 967, in <module>
    sample_1052()
  File "E:/abu-master/python/c10.py", line 914, in sample_1052
    from abupy.UmpBu.ABuUmpMainMul import UmpMulFiter
ImportError: cannot import name 'UmpMulFiter'`

你好，在运行完毕sample_1052之前的所有函数后（包括c1-c9），单独运行sample_1052，出现以上错误信息，我查看了abupy的源码，发现UmpMulFiter为ABuUmpMainMul的内部类，但是使用
`from abupy.UmpBu.ABuUmpMainMul import ABuUmpMainMul`
会出现cannot import的错误，请问此处应如何解决？

**Comment by bbfamily** [comment]
您好，python3.4以下对内部类notebook导入存在问题，github上的代码都已经修改了不使用内部类，请更新github代码，如果您是最新的代码，有可能是因为使用pip安装了老版本的abupy，导致python的c10代码优先import了pip安装的abupy, 建议运行ipython下的第10章示例（ipython notebbok版本优先使用示例代码同层的abupy），或者使用pip更新abupy，祝好！

**Comment by ZJianjin** [comment]
你好，我使用的是python3.6，对于内部类导入仍然有问题。此外，直接使用pip install abupy安装为0.3.0版本，其源码文件仍然使用了内部类，但在github上看到已经不再使用内部类，因此只能通过运行setup.py安装。在同一个函数中后面引入的UmpDegFiter似乎应在ABuUmpMainDeg包中，源码上所写的似乎是ABuUmpMainBase。
在运行c11.py之前是否需要其他准备？我直接运行后显示如下错误：
`C:\Python36\python.exe E:/abu-master/python/c11.py
load_pickle file_name=C:\Users\PINC\abu\data\cache\n5_train_cn_capital not exists!
load_pickle file_name=C:\Users\PINC\abu\data\cache\n5_train_cn_benchmark not exists!
load_pickle file_name=C:\Users\PINC\abu\data\cache\n5_test_cn_capital not exists!
load_pickle file_name=C:\Users\PINC\abu\data\cache\n5_test_cn_benchmark not exists!
metrics input is invalid or zero order gen!
metrics input is invalid or zero order gen!
Traceback (most recent call last):
  File "E:/abu-master/python/c11.py", line 361, in <module>
    sample_111()
  File "E:/abu-master/python/c11.py", line 88, in sample_111
    plot_simple = orders_pd_train[orders_pd_train.profit_cg < 0][:20]
AttributeError: 'NoneType' object has no attribute 'profit_cg`

**Comment by bbfamily** [comment]
pip上的版本不是最新的，不建议直接运行c11，c11的运行基础是在运行https://github.com/bbfamily/abu/tree/master/abupy_lecture中的第20节之后的有本地缓存后才可以运行，c11上有注明需要的运行环境
