### ISSUE TITLE
c11中ValueError: cannot convert float NaN to integer错误

### ISSUE THREAD

**Issue by ZJianjin** [bbfamily/abu#9]
你好，在c11.py文件中运行sample_112()，sample_1124()，sample_1125()三个函数的时候，都会有如下错误：
`C:\Python36\lib\site-packages\numpy\lib\index_tricks.py:178: RuntimeWarning: invalid value encountered in double_scalars
  int(math.ceil((key[k].stop - start)/(step*1.0))))
Traceback (most recent call last):
  File "E:/abu-master/python/c11.py", line 362, in <module>
    sample_112()
  File "E:/abu-master/python/c11.py", line 158, in sample_112
    brust_min = ump_deg.brust_min()
  File "C:\Python36\lib\site-packages\abupy-0.2.0-py3.6.egg\abupy\UmpBu\ABuUmpMainBase.py", line 731, in brust_min
    brust_result = sco.brute(self.min_func_improved, bnds, full_output=False, finish=None)
  File "C:\Python36\lib\site-packages\scipy\optimize\optimize.py", line 2822, in brute
    grid = mgrid[lrange]
  File "C:\Python36\lib\site-packages\numpy\lib\index_tricks.py", line 178, in __getitem__
    int(math.ceil((key[k].stop - start)/(step*1.0))))
ValueError: cannot convert float NaN to integer`
环境python3.6，请问该如何处理？

**Comment by bbfamily** [comment]
您好，c11需要在第20节内容完成运行后有A股训练集交易和A股测试集交易数据之后，我无法知道您具体的训练结果以及过程，且如果运行完第20节教程后直接进行后面的教程运行就可以，没有必要再运行c11

**Comment by ZJianjin** [comment]
第20节已运行且没有报错，其两次show_general结果如下：

买入后卖出的交易数量:55312
买入后尚未卖出的交易数量:959
胜率:47.2031%
平均获利期望:15.3682%
平均亏损期望:-7.7931%
盈亏比:1.9754
策略收益: 105.3649%
基准收益: 52.5454%
策略年化收益: 21.8715%
基准年化收益: 10.9073%
策略买入成交比例:30.4917%
策略资金利用率比例:75.8702%
策略共执行1214个交易日

买入后卖出的交易数量:6289
买入后尚未卖出的交易数量:122
胜率:47.0822%
平均获利期望:25.8019%
平均亏损期望:-7.5227%
盈亏比:2.1408
策略收益: 207.0707%
基准收益: 52.5454%
策略年化收益: 42.9834%
基准年化收益: 10.9073%
策略买入成交比例:37.2485%
策略资金利用率比例:70.4231%
策略共执行1214个交易日

如果需要其他结果信息我也可以再发出来，因为我是买的书，c11对应第11章的内容，所以希望它能够完整运行，能否麻烦您帮忙解决一下？谢谢

**Comment by bbfamily** [comment]
您好，如果第20节可以正常运行就可以继续运行教程之后的章节，实际上书的第11章没有办法写全写明白所有相关ump的内容，所以才后来写的完整教程，而且书里的相关运行环境无法复原，和书之前的章节不一样，之前的章节使用的全部是内置沙盒数据所以运行结果是一致的，但c11并没有原始运行环境，所以才写了补充教程使用云盘上的csv压缩数据，您直接运行教程之后的章节就可以了，如后面的第21节也存在问题建议您检查一下使用的环境是不是在教程第0节中建议使用的conda 4.4版本。

我无法对单独问题，个体环境等进行辅助跟踪调试解决，对不住，因为我真没时间，我和其他做开源的不一样，我没想通过开源挣钱，什么项目打赏，做什么培训，没有时间，说白了其实就是没想挣你们的钱（当然我并不是说其它做开源的不好，只是我没有对个人进行帮助的原始动力），希望理解，本来一开始只是写书时想开源一部分，后来觉着既然开源了，会用得写个教程，但是现在感觉占用我时间太多，我是靠自己的交易时间挣钱，祝好！
另外建议您可以尝试自行调试解决问题，因为量化最终要做出还得要靠自己独立思考，独立交易，加油。
